DROP TABLE IF EXISTS WMF_EXECUTED_JOB;
DROP TABLE IF EXISTS WMF_EXECUTED_JOB_LOG;

create table WMF_EXECUTED_JOB
(
ID BIGINT NOT NULL AUTO_INCREMENT,
JOB_NAME VARCHAR(200) NOT NULL,
JOB_GROUP VARCHAR(200) NOT NULL,
START_TIME datetime NOT NULL,
ELAPSED_TIME BIGINT NOT NULL,
EXECUTE_STATUS TINYINT NOT NULL,
PRIMARY KEY (ID)
)
ENGINE=InnoDB;

create table WMF_EXECUTED_JOB_LOG
(
ID BIGINT NOT NULL AUTO_INCREMENT,
EXECUTED_JOB_ID BIGINT NOT NULL,
TIME datetime NOT NULL,
LEVEL TINYINT NOT NULL,
MESSAGE VARCHAR(1024) NOT NULL,
PRIMARY KEY (ID)
)
ENGINE=InnoDB;

